/**
 * Real implementation of `context` on the new blueprint (see the `context`
 * case in ../index.ts). Blueprint only - no real DB is touched; the context
 * backend is injected, defaulting to a safe simulated implementation.
 *
 * Generates project context (recent sessions, hot files, git activity, errors,
 * usage) and writes to .smriti/CLAUDE.md for token reduction. No required args;
 * project is auto-detected from cwd, days defaults to 7.
 */

import type { Database } from "bun:sqlite";
import { BaseCommand, type ParsedArgs } from "../command";
import type { ArgSpec, FlagSpec, Example } from "../help/types";
import { generateContext as realGenerateContext } from "../context";

export interface ContextResult {
  projectId: string;
  context: string;
  written: boolean;
  path: string | null;
  tokenEstimate: number;
}

export interface ContextOptions {
  project?: string;
  days?: number;
  dryRun?: boolean;
}

/** Injected backend seams - default simulations, no real DB access. */
export interface ContextBackend {
  /** Generate project context and optionally write to file. */
  generateContext(options: ContextOptions): Promise<ContextResult>;
}

const simulateBackend: ContextBackend = {
  async generateContext(options) {
    const projectId = options.project || "myproject";
    const days = options.days || 7;
    const contextText = `## Project Context

> Auto-generated by \`smriti context\` on 2026-08-06. Do not edit manually.

### Recent Sessions (last ${days} days)
- **just now** Feature: add context command (2 turns) [development]
- **1h ago** Fix: memory search regression (5 turns) [bugfix]

### Hot Files
\`src/commands/context.ts\` (3 ops), \`src/command.ts\` (2 ops)

### Usage
2 sessions, 7 turns, ~5K input / ~3K output tokens`;

    return {
      projectId,
      context: contextText,
      written: !options.dryRun,
      path: !options.dryRun ? `.smriti/CLAUDE.md` : null,
      tokenEstimate: Math.ceil(contextText.length / 4),
    };
  },
};

/**
 * Real backend - delegates to the actual context generator in ../context.ts
 * (same function `smriti context` calls today via the `context` case in
 * ../index.ts: `generateContext(db, { project, days, dryRun, json })`).
 *
 * Not wired as the default; pass explicitly via
 * `new ContextCommand(createRealContextBackend(db))`.
 */
export function createRealContextBackend(db: Database): ContextBackend {
  return {
    async generateContext(options) {
      return realGenerateContext(db, {
        project: options.project,
        days: options.days,
        dryRun: options.dryRun,
      });
    },
  };
}

export class ContextCommand extends BaseCommand<ContextResult> {
  constructor(private readonly backend: ContextBackend = simulateBackend) {
    super();
  }

  name = "context";
  summary = "Generate project context for .smriti/CLAUDE.md";
  args: ArgSpec[] = [];
  flags: FlagSpec[] = [
    { flag: "--project", type: "string", description: "project filter (auto-detect from cwd)" },
    { flag: "--days", type: "number", default: "7", description: "lookback window in days" },
    { flag: "--dry-run", type: "boolean", description: "print to stdout, don't write file" },
  ];
  output = {
    description: "prints generated context; with --json returns { projectId, context, written, path, tokenEstimate }",
    jsonShape: "{ projectId: string, context: string, written: boolean, path: string | null, tokenEstimate: number }",
  };
  examples: [Example, Example, Example] = [
    {
      command: "smriti context",
      description: "auto-detect project, write to .smriti/CLAUDE.md",
    },
    {
      command: "smriti context --project myapp --days 30",
      description: "generate context for myapp over the last 30 days",
    },
    {
      command: "smriti context --dry-run",
      description: "preview context without writing to file",
    },
  ];
  detailedSummary =
    "Gathers recent sessions, hot files, git activity, and error trends from project memory. " +
    "Generates a compact markdown block and splices it into .smriti/CLAUDE.md. " +
    "Idempotent — running twice produces the same result. " +
    "Project is auto-detected from cwd (registered path or directory basename as ID); " +
    "override with --project. Days defaults to 7; token estimate is context length ÷ 4. " +
    "--dry-run prints context without writing.";

  protected async execute(parsed: ParsedArgs): Promise<ContextResult> {
    const project = parsed.flags["--project"] as string | undefined;
    const days = parsed.flags["--days"]
      ? Number(parsed.flags["--days"])
      : undefined;
    const dryRun = parsed.flags["--dry-run"] === true;

    return this.backend.generateContext({
      project,
      days,
      dryRun,
    });
  }
}
