/**
 * cluster.ts - Semantic session clustering (#66)
 *
 * k-means clustering over session embeddings (content_vectors seq=0).
 * Cluster names generated by Ollama. Results persisted to smriti_session_clusters.
 */

import type { Database } from "bun:sqlite";
import { ollamaChat } from "./ollama";

// =============================================================================
// Types
// =============================================================================

export type Cluster = {
  id: number;
  name: string;
  sessionIds: string[];
  lastActive: string | null;
};

export type ClusterResult = {
  clusters: Cluster[];
  totalSessions: number;
};

// =============================================================================
// k-means Implementation
// =============================================================================

function cosineDistance(a: Float32Array, b: Float32Array): number {
  let dot = 0, normA = 0, normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i]! * b[i]!;
    normA += a[i]! * a[i]!;
    normB += b[i]! * b[i]!;
  }
  if (normA === 0 || normB === 0) return 1;
  return 1 - dot / (Math.sqrt(normA) * Math.sqrt(normB));
}

function centroid(vectors: Float32Array[]): Float32Array {
  if (vectors.length === 0) return new Float32Array(0);
  const dim = vectors[0]!.length;
  const sum = new Float32Array(dim);
  for (const v of vectors) {
    for (let i = 0; i < dim; i++) sum[i]! += v[i]!;
  }
  for (let i = 0; i < dim; i++) sum[i]! /= vectors.length;
  return sum;
}

function kmeans(vectors: Float32Array[], k: number, maxIter = 20): number[] {
  if (vectors.length === 0 || k <= 0) return [];
  const n = vectors.length;
  k = Math.min(k, n);

  // Deterministic initialization: pick evenly spaced indices
  const centroids: Float32Array[] = [];
  for (let i = 0; i < k; i++) {
    centroids.push(vectors[Math.floor((i * n) / k)]!);
  }

  let assignments = new Array(n).fill(0);

  for (let iter = 0; iter < maxIter; iter++) {
    // Assign each vector to nearest centroid
    const newAssignments = vectors.map(v => {
      let bestCluster = 0;
      let bestDist = Infinity;
      for (let c = 0; c < k; c++) {
        const d = cosineDistance(v, centroids[c]!);
        if (d < bestDist) { bestDist = d; bestCluster = c; }
      }
      return bestCluster;
    });

    // Check convergence
    if (newAssignments.every((a, i) => a === assignments[i])) break;
    assignments = newAssignments;

    // Update centroids
    for (let c = 0; c < k; c++) {
      const clusterVecs = vectors.filter((_, i) => assignments[i] === c);
      if (clusterVecs.length > 0) centroids[c] = centroid(clusterVecs);
    }
  }

  return assignments;
}

// =============================================================================
// Cluster Name Generation
// =============================================================================

async function nameCluster(titles: string[], model?: string): Promise<string> {
  try {
    const resp = await ollamaChat([
      {
        role: "system",
        content:
          "You name topic clusters from a list of session titles. " +
          "Return ONLY a concise 2-5 word phrase (no punctuation) that captures the common theme.",
      },
      {
        role: "user",
        content: `Session titles:\n${titles.slice(0, 10).join("\n")}`,
      },
    ], { temperature: 0.2, maxTokens: 16, model });
    return resp.message.content.trim().replace(/[.!?"]$/, "");
  } catch {
    return `cluster-${titles[0]?.slice(0, 20) ?? "unknown"}`;
  }
}

// =============================================================================
// Main Cluster Function
// =============================================================================

export async function clusterSessions(
  db: Database,
  options: {
    projectId?: string;
    k?: number;
    model?: string;
  } = {}
): Promise<ClusterResult> {
  // Load session embeddings (first chunk per session)
  const sessionQuery = options.projectId
    ? `SELECT mm.session_id, cv.hash || '_' || cv.seq as hash_seq
       FROM memory_messages mm
       JOIN content_vectors cv ON cv.hash = mm.hash AND cv.seq = 0
       JOIN smriti_session_meta sm ON sm.session_id = mm.session_id
       WHERE sm.project_id = ?
       GROUP BY mm.session_id`
    : `SELECT mm.session_id, cv.hash || '_' || cv.seq as hash_seq
       FROM memory_messages mm
       JOIN content_vectors cv ON cv.hash = mm.hash AND cv.seq = 0
       GROUP BY mm.session_id`;

  const rows = options.projectId
    ? (db as any).prepare(sessionQuery).all(options.projectId) as { session_id: string; hash_seq: string }[]
    : (db as any).prepare(sessionQuery).all() as { session_id: string; hash_seq: string }[];

  if (rows.length < 2) {
    return { clusters: [], totalSessions: rows.length };
  }

  // Load actual embedding vectors from vectors_vec
  const sessionIds = rows.map(r => r.session_id);
  const hashSeqs = rows.map(r => r.hash_seq);

  const embeddingRows = (db as any).prepare(
    `SELECT hash_seq, embedding FROM vectors_vec WHERE hash_seq IN (${hashSeqs.map(() => "?").join(",")})`
  ).all(...hashSeqs) as { hash_seq: string; embedding: Buffer }[];

  const embeddingMap = new Map(embeddingRows.map(r => [r.hash_seq, new Float32Array(r.embedding.buffer)]));

  // Filter to sessions with embeddings
  const validRows = rows.filter(r => embeddingMap.has(r.hash_seq));
  if (validRows.length < 2) {
    return { clusters: [], totalSessions: rows.length };
  }

  const vectors = validRows.map(r => embeddingMap.get(r.hash_seq)!);
  const k = options.k ?? Math.max(2, Math.min(20, Math.round(Math.sqrt(validRows.length / 2))));

  // Run k-means
  const assignments = kmeans(vectors, k);

  // Group session IDs by cluster
  const clusterMap = new Map<number, string[]>();
  for (let i = 0; i < assignments.length; i++) {
    const cid = assignments[i]!;
    if (!clusterMap.has(cid)) clusterMap.set(cid, []);
    clusterMap.get(cid)!.push(validRows[i]!.session_id);
  }

  // Load session titles + last active dates
  const sessionTitleRows = (db as any).prepare(
    `SELECT id, title, updated_at FROM memory_sessions WHERE id IN (${sessionIds.map(() => "?").join(",")})`
  ).all(...sessionIds) as { id: string; title: string; updated_at: string }[];
  const titleMap = new Map(sessionTitleRows.map(r => [r.id, { title: r.title, updated_at: r.updated_at }]));

  // Generate cluster names + persist
  (db as any).prepare(`DELETE FROM smriti_session_clusters WHERE session_id IN (${sessionIds.map(() => "?").join(",")})`).run(...sessionIds);

  const insertStmt = (db as any).prepare(
    `INSERT OR REPLACE INTO smriti_session_clusters(session_id, cluster_id, cluster_name, distance) VALUES (?, ?, ?, ?)`
  );

  const clusters: Cluster[] = [];
  for (const [cid, sids] of clusterMap) {
    const titles = sids.map(sid => titleMap.get(sid)?.title || sid).filter(Boolean);
    const name = await nameCluster(titles, options.model);
    const lastActive = sids.reduce<string | null>((best, sid) => {
      const d = titleMap.get(sid)?.updated_at ?? null;
      if (!best || (d && d > best)) return d;
      return best;
    }, null);

    for (const sid of sids) {
      insertStmt.run(sid, cid, name, 0);
    }

    clusters.push({ id: cid, name, sessionIds: sids, lastActive });
  }

  clusters.sort((a, b) => b.sessionIds.length - a.sessionIds.length);
  return { clusters, totalSessions: validRows.length };
}

// =============================================================================
// Cluster Lookup (for --cluster filter in recall)
// =============================================================================

export function getClusterSessionIds(db: Database, clusterName: string): string[] {
  const rows = (db as any).prepare(
    `SELECT DISTINCT session_id FROM smriti_session_clusters WHERE LOWER(cluster_name) LIKE LOWER(?)`
  ).all(`%${clusterName}%`) as { session_id: string }[];
  return rows.map(r => r.session_id);
}
